name: CI Pipeline with Docker

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Run tests (you should already have tests defined)
    - name: Run tests
      run: npm test

    # Step 5: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t your-dockerhub-username/sample-app:latest .

    # Step 6: Login to DockerHub using your GitHub secrets
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME_SAMPLETEST }}
        password: ${{ secrets.DOCKER_PASSWORD_MZOTSHO2024 }}

    # Step 7: Push Docker image to Docker Hub
    - name: Push Docker image to DockerHub
      run: |
        docker push your-dockerhub-username/sample-app:latest
